services:
  - type: web
    name: schedule-planner
    env: node
    region: oregon
    plan: free
    buildCommand: chmod +x ./render-build.sh && ./render-build.sh
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9
    scaling:
      minInstances: 1
      maxInstances: 1 